services:
  back:
    build:
      context: ..
      dockerfile: docker/back.Dockerfile
    volumes:
      - ../back:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  front:
    build:
      context: ..
      dockerfile: docker/front.Dockerfile
    volumes:
      - ../front:/app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    depends_on:
      - back
